services:
  mongodb:
    container_name: polymorphic-mongo
    image: 'mongo:8.2.4'
    environment:
      - 'MONGO_INITDB_DATABASE=polymorphic_chat'
      - 'MONGO_INITDB_ROOT_PASSWORD=polymorphic'
      - 'MONGO_INITDB_ROOT_USERNAME=polymorphic'
    ports:
      - '27017:27017'
  redis:
    container_name: polymorphic-redis
    image: 'redis:8.4.0'
    ports:
      - '6379:6379'
