spring:
  application:
    name: Polymorphic Chat
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: polymorphic_chat
    username: ${MONGODB_USER:polymorphic}
    password: ${MONGODB_PASSWORD:polymorphic}
    authentication-database: admin

security:
  bcrypt:
    strength: ${BCRYPT_STRENGTH:12}
  jwt:
    secret: ${JWT_SECRET:OPGUxztUJ0+mj5rWoolwe+bxQ7glv3GpLyIrC4PIEMU=}
  token:
    access:
      expiration: 300
    refresh:
      expiration: 2592000

app:
  cookies:
    secure: true
    same-site: Lax

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:local.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: local

ai:
  cohere:
    base-url: https://api.cohere.com
    api-key: ${COHERE_API_KEY}
    model: command-a-03-2025